import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root='demos/design-v1', data='var/evidence/continuation-20260930/native-stage389-data/data';
const snap=JSON.parse(fs.readFileSync(data+'/demo-snapshot.json'));const ents=JSON.parse(fs.readFileSync(data+'/entities.json'));const files=new Map();
function walk(p){for(const e of fs.readdirSync(p,{withFileTypes:true})){let q=path.join(p,e.name);if(e.isDirectory())walk(q);else if(/^[a-f0-9]{64}\.(jpg|png|webp|jpeg)$/.test(e.name)&&!files.has(e.name))files.set(e.name,q);}}walk('var/pilots');
const products=[];for(const p of snap.items.filter(p=>p.is_product)){const entity=ents.find(e=>e.source_id===p.id);const pic=entity?.blocks.find(b=>b.type==='image'&&/\/catalog\//.test(b.source_url)&&!/96x96/.test(b.source_url));const name=pic?[...files.keys()].find(n=>n.startsWith(pic.asset_sha256+'.')):null;if(!name)continue;const f=files.get(name);if(!f)continue;const bytes=fs.readFileSync(f);if(crypto.createHash('sha256').update(bytes).digest('hex')!==name.split('.')[0])continue;fs.copyFileSync(f,root+'/assets/'+name);const en=ents.find(e=>e.source_id===p.id);let desc='';let started=false;for(const b of en?.blocks||[]){if(b.type==='heading'){if(started)break;if(b.text==='Описание')started=true;}else if(started&&b.type==='paragraph'&&desc.length<700)desc+=b.text+'\n';}let category=/termoregulyatory/.test(p.request_target)?'Терморегуляторы':/нагревательный мат|нагревательные маты/i.test(p.title)?'Нагревательные маты':/кабел/i.test(p.title)?'Нагревательный кабель':/пленочный теплый пол|плёночный тёплый пол/i.test(p.title)?'Плёночный пол':'Аксессуары';products.push({id:p.id,name:p.title.split(': цена')[0].split('|')[0].trim(),image:'assets/'+name,category,description:desc.trim(),attributes:p.attributes,source:'https://teplypol-market.ru'+p.request_target});}
products.sort((a,b)=>Number(b.category==='Нагревательные маты')-Number(a.category==='Нагревательные маты'));
fs.writeFileSync(root+'/products.js','window.PRODUCTS='+JSON.stringify(products).replaceAll('<','\\u003c')+';');console.log('Verified product images:',products.length);


