import {catalogPlan,qualityIssues} from './catalog.mjs';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import * as cheerio from 'cheerio';
import {chromium} from 'playwright';
const ROOT=path.dirname(fileURLToPath(import.meta.url));
const vendor=path.join(ROOT,'vendor/hyperui');
const manifest=JSON.parse(fs.readFileSync(path.join(vendor,'manifest.json')));
export const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).replace(/\s+/g,' ').trim();
const excluded=/₽|руб\.|в наличии|скидк|акци[яи]|товаров:|cookie|captcha|killbot|парол|политик[аи]|согласие на|персональн|©|в корзину|заказать звонок/i;
function template(name){const relative='public/examples/marketing/'+name+'/1.html';const bytes=fs.readFileSync(path.join(vendor,relative));if(hash(bytes)!==manifest.files.find(x=>x.path===relative)?.sha256)throw Error('HYPERUI_INTEGRITY');return cheerio.load(bytes.toString());}
export function plan(source,direction='auto'){
 const categories=catalogPlan(source);const corpus=norm(source.text);if(corpus.length<150)throw Error('SOURCE_TOO_SHORT');
 const lines=[...new Set(String(source.text).split(/\n+/).map(norm).filter(Boolean))];
 const suitable=x=>x.length>=65&&x.length<=550&&!excluded.test(x)&&/[.!?](?:$|\s)/.test(x)&&!/(?:@|\bhttps?:|улиц[аые]|этаж|офис|ТРК|Cookie)/i.test(x);
 const structured=(source.structure?.paragraphs||[]).filter(x=>corpus.includes(norm(x.text))&&suitable(norm(x.text)));
 const paras=[...new Set((structured.length>=2?structured.map(x=>norm(x.text)):lines).filter(suitable))];
 if(paras.length<2)throw Error('HTML_SOURCE_INSUFFICIENT');
 const h1=(source.structure?.headings||[]).find(x=>x.level===1&&x.text.length>8&&x.text.length<150&&!excluded.test(x.text)&&corpus.includes(norm(x.text)))?.text;
 const headline=norm(h1||source.title||new URL(source.url).hostname).slice(0,200);
 const headings=[...new Set((source.structure?.headings||[]).map(x=>norm(x.text)).filter(x=>x.length>5&&x.length<75&&corpus.includes(x)&&!excluded.test(x)))];
 const topics=headings.filter(x=>x!==headline).slice(0,6);
 const paragraphs=paras.slice(0,6);const cardHeadings=paragraphs.slice(1,4).map(text=>{const h=structured.find(x=>norm(x.text)===text)?.heading;return h&&norm(h)!==headline&&corpus.includes(norm(h))&&norm(h).length<75&&!structured.slice(0,structured.findIndex(x=>norm(x.text)===text)).some(x=>norm(x.heading)===norm(h))?norm(h):null});
 const textBlocks=[...paragraphs.map(text=>({text,source_url:source.url,offset:source.text.indexOf(text),method:'verbatim-normalized'})),...topics.map(text=>({text,source_url:source.url,method:'verbatim-normalized'}))];
 for(const b of textBlocks)if(!corpus.includes(norm(b.text)))throw Error('UNSOURCED_TEXT');
 const emails=[...new Set(lines.filter(x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)))].slice(0,2);
 const phones=[...new Set(lines.filter(x=>/^\+?[\d()\s-]{10,24}$/.test(x)&&/[()-]/.test(x)))].slice(0,2);
 return {version:2,categories,kind:'html',direction:['auto','minimal','expressive','premium'].includes(direction)?direction:'auto',brand:new URL(source.url).hostname.replace(/^www\./,''),headline,paragraphs,cardHeadings,topics,emails,phones,evidence:textBlocks,source_url:source.url,observed_at:source.observed_at,source_sha256:hash(JSON.stringify(source)),hyperui:{commit:manifest.commit,components:['headers/1','sections/1','cards/1','footers/1']},limitations:['Дословные фрагменты страницы, а не подтверждение достоверности заявлений владельца.','Название домена используется вместо логотипа.','Формы, заказы и платежи отсутствуют.','Первый набор композиций; не перенос всего сайта.']};
}
function visual(source,sourceDir){
 if(source.structure?.categories?.length)return '';
 const entry=(source.images||[]).filter(x=>/^source-media-\d+\.(png|jpg|webp)$/.test(x.file)&&x.width>=400&&x.height>=180).sort((a,b)=>(b.width*b.height)-(a.width*a.height))[0];
 if(!entry)return '<div class="abstract" aria-hidden="true"><span></span><span></span><span></span><i></i></div>';
 const bytes=fs.readFileSync(path.join(sourceDir,entry.file));if(bytes.length>2_000_000||hash(bytes)!==entry.sha256)throw Error('SOURCE_MEDIA_INTEGRITY');
 const types={png:'image/png',jpg:'image/jpeg',webp:'image/webp'};return '<figure class="source-visual"><img src="data:'+types[entry.file.split('.').pop()]+';base64,'+bytes.toString('base64')+'" alt="'+escape(entry.alt||'Изображение исходного сайта')+'"><figcaption>Изображение исходной страницы</figcaption></figure>';
}
export function render(source,model,sourceDir){
 const $hero=template('sections');const hero=$hero('body > section');hero.attr('class','hero').attr('id','top');hero.find('h2').replaceWith('<h1>'+escape(model.headline)+'</h1>');hero.find('p').text(model.paragraphs[0]);hero.find('h1').before('<p class="eyebrow">'+escape(model.brand)+'</p>');hero.find('p').last().after('<a class="action" href="#content">Смотреть содержание <span aria-hidden="true">↗</span></a>');hero.find('img').replaceWith(visual(source,sourceDir));
 const $header=template('headers');const header=$header('body header').first();header.attr('class','site-header').empty().append('<div class="mx-auto flex max-w-7xl items-center justify-between gap-6 px-4 py-6 sm:px-6 lg:px-8"><a class="wordmark" href="#top">'+escape(model.brand)+'</a><nav aria-label="Разделы страницы"><a href="#content">Информация</a><a href="#details">Подробнее</a><a href="#contacts">Контакты</a></nav><a class="header-cta" href="#source-evidence">Источник ↗</a></div>');
 let cards=model.paragraphs.slice(1,4).map((text,i)=>{const $=template('cards');const card=$('body > a').first();card.attr('href','#source-evidence').attr('class',card.attr('class')+' content-card');card.find('img').parent().remove();card.find('dl').remove();card.find('h3').text(model.cardHeadings[i]||'Информация '+String(i+1).padStart(2,'0'));card.find('p').first().text('0'+(i+1)).attr('class','card-index');card.find('p').last().text(text).attr('class','card-text');return $.html(card)}).join('');
 if(model.categories.length){
  cards=model.categories.map(c=>{const entry=(source.images||[]).find(x=>x.url===c.image_url);let image='';if(entry&&/^source-media-\d+\.(png|jpg|webp)$/.test(entry.file)){const bytes=fs.readFileSync(path.join(sourceDir,entry.file));if(bytes.length>2_000_000||hash(bytes)!==entry.sha256)throw Error('SOURCE_MEDIA_INTEGRITY');image='<img alt="'+escape(c.name)+'" src="data:image/'+(entry.file.endsWith('.jpg')?'jpeg':entry.file.split('.').pop())+';base64,'+bytes.toString('base64')+'">'}return '<a class="category-card" data-source-category="'+escape(c.url)+'" href="'+escape(c.url)+'" target="_blank" rel="noopener noreferrer">'+image+'<h3>'+escape(c.name)+'</h3><span>На исходном сайте ↗</span></a>'}).join('');
  hero.addClass('catalog-hero');hero.find('.action').text('Выбрать категорию');header.find('nav a[href="#content"]').text('Каталог');
 }
 const $footer=template('footers');const footer=$footer('body footer').first();footer.attr('class','site-footer').empty().append('<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><strong>'+escape(model.brand)+'</strong><p>HTML-концепция · текстовое название вместо логотипа</p><p>Компоненты адаптированы из HyperUI (MIT).</p><a href="#top">К началу страницы ↑</a></div>');
 const details=model.paragraphs.slice(4).map(x=>'<p class="detail-text">'+escape(x)+'</p>').join('')||'<p class="detail-text">'+escape(model.paragraphs[1])+'</p>';
 const evidence=model.evidence.map(x=>'<li>'+escape(x.text)+'</li>').join('');
 const css=fs.readFileSync(path.join(ROOT,'design.css'),'utf8');const license=fs.readFileSync(path.join(vendor,'LICENSE'),'utf8').replace(/--/g,'—');
 return '<!doctype html><html lang="ru" data-direction="'+model.direction+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:; base-uri \'none\'; form-action \'none\'"><title>'+escape(model.brand)+' — HTML-концепция</title><style>'+css+'</style></head><body><a class="skip" href="#content">К содержанию</a><div class="demo-bar">Концепция дизайна · формы, заказы и платежи отключены</div>'+$header.html(header)+'<main>'+$hero.html(hero)+'<section class="content-section" id="content"><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div class="section-heading"><p class="eyebrow">'+(model.categories.length?'Каталог':'О компании')+'</p><h2>'+(model.categories.length?'Категории продукции':'Информация о компании')+'</h2></div><div class="grid grid-cols-1 gap-6 md:grid-cols-3">'+cards+'</div></div></section><section id="details" class="detail-section"><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div class="grid grid-cols-1 gap-8 md:grid-cols-2"><h2>Подробнее</h2><div>'+details+'</div></div></div></section><section id="contacts" class="contact-section"><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p class="eyebrow">Контакты из источника</p><h2>'+escape(model.emails[0]||model.brand)+'</h2><p class="contact-phone">'+escape(model.phones[0]||'Контакты уточняйте на исходном сайте')+'</p><p>Контактные данные показаны справочно. Отправка обращений в макете отсутствует.</p></div></section><section id="source-evidence" class="evidence-section"><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><details><summary>Источник, дата и использованные фрагменты</summary><p>'+escape(source.url)+' · '+escape(source.observed_at)+'</p><ol>'+evidence+'</ol><ul>'+model.limitations.map(x=>'<li>'+escape(x)+'</li>').join('')+'</ul></details></div></section></main>'+$footer.html(footer)+'<!-- HyperUI attribution\n'+license+' --></body></html>';
}
export async function createHtmlConcept({source,sourceDir,outputDir,direction}){
 const model=plan(source,direction);const html=render(source,model,sourceDir);const semanticIssues=qualityIssues(html,model);if(semanticIssues.length)throw Error(semanticIssues.join(','));fs.writeFileSync(path.join(outputDir,'concept.html'),html,{flag:'wx'});
 const browser=await chromium.launch({headless:true,env:{PATH:process.env.PATH,HOME:process.env.HOME,LANG:'C.UTF-8'},args:['--proxy-server=http://127.0.0.1:9','--proxy-bypass-list=<-loopback>','--disable-background-networking']});
 let report;
 try{const c=await browser.newContext({viewport:{width:1536,height:1000},javaScriptEnabled:false,serviceWorkers:'block'});let requests=0;await c.route('**/*',r=>{requests++;return r.abort()});const p=await c.newPage();await p.setContent(html,{waitUntil:'load'});const desktopOverflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);const height=await p.evaluate(()=>document.documentElement.scrollHeight);if(height>15000)throw Error('HTML_HEIGHT_LIMIT');await p.screenshot({path:path.join(outputDir,'concept.png'),fullPage:true});await p.setViewportSize({width:390,height:844});const mobileOverflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await p.screenshot({path:path.join(outputDir,'concept-mobile.png'),fullPage:true});const headings=await p.locator('h1').count();const unsafe=await p.locator('script,form,iframe,object,embed,input,button').count();report={pass:!desktopOverflow&&!mobileOverflow&&headings===1&&unsafe===0&&requests===0,desktopOverflow,mobileOverflow,external_requests:requests,h1:headings,unsafe_elements:unsafe,width:1536,height,checked_at:new Date().toISOString(),checks:['browser-layout','source-exact-text','no-active-content','unique-card-headings','catalog-coverage','catalog-images'],issues:[],summary:'Текст взят из сохранённого источника. Проверены ширина страницы и отсутствие внешних запросов. Визуальная оценка человеком отдельно.'};if(!report.pass)report.issues.push('Не пройдена структурная или браузерная проверка HTML.');}finally{await browser.close()}
 model.files={html:hash(html),png:hash(fs.readFileSync(path.join(outputDir,'concept.png')))};model.review=report;fs.writeFileSync(path.join(outputDir,'concept.model.json'),JSON.stringify(model,null,2),{flag:'wx'});return {kind:'html',brief:{business:model.headline,direction:'HTML-композиция из компонентов HyperUI',facts:model.evidence,problems:[],changes:['Текст отображается средствами браузера.','Адаптивная сетка и навигация по разделам.','Самодостаточный HTML без внешних скриптов.'],limitations:model.limitations,assumptions:[]},review:report,width:1536,height:report.height,source_url:source.url,observed_at:source.observed_at,logo:'Домен вместо исходного логотипа',cost:'Для HTML-версии платные API не вызываются',automatic_review:true,hyperui:model.hyperui};
}
